[package]
name = "dbgame-test"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.5.0"
image = { version = "0.25.8", default-features = false, features = ["png"] }
sdk = { path = "../sdk" }
