[package]
name = "sdk"
version = "0.1.0"
edition = "2024"
authors = ["Aurora", "Hazel Stagner"]
license = "MIT"

[dependencies]
libm = "0.2.15"
bitflags = "2.9.4"
dbsdk-vu-asm = "0.1.0"

[features]
default = ["std"]
std = ["bitflags/std"]
